added: login-signup pages
rkapoor10/ecommerce pull request #6
Opened 2022-02-12 20:50 UTC by rkapoor10

- LOGIN PAGE

![login page](https://user-images.githubusercontent.com/61417822/153727893-eab2f9ff-5ed5-4853-8b2f-d416e1918eca.PNG)

- SIGN UP PAGE

![signup](https://user-images.githubusercontent.com/61417822/153727907-39fdf45c-f82d-4fbf-b21b-7adf16e04ed1.PNG)

2022-02-13 09:04 UTC, tusharkandpal approved these changes
Good to merge!

2022-02-13 09:04 UTC, tusharkandpal commented on login/login.html
> +                <p class="fs-07 baseteal">Smashinn Badminton Products your way</p>
if its a typo, correct it `Smashinn`

2022-02-13 09:11 UTC, t007rushi requested changes
check-box is missing before T&C

2022-02-16 12:36 UTC, rkapoor10 commented on login/login.html
> +                <p class="fs-07 baseteal">Smashinn Badminton Products your way</p>
no its not

2022-02-16 13:41 UTC, t007rushi approved these changes

2022-02-18 21:29 UTC, merged